/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package humanresourcemanagement;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {
    
    Driver driver = new Driver();
    ArrayList<Department> departments = new ArrayList<Department>();

    /*
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        
        try {
            departments = driver.readProgress();
            computerScienceDepartment.setText(departments.get(0).display());
            liberalArtsDepartment.setText(departments.get(1).display());
            businessDepartment.setText(departments.get(2).display());
            
        } catch (Exception e){
            driver.initialize();
            departments = driver.readProgress();
            computerScienceDepartment.setText(departments.get(0).display());
            liberalArtsDepartment.setText(departments.get(1).display());
            businessDepartment.setText(departments.get(2).display());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        teacherGenderGroup = new javax.swing.ButtonGroup();
        teacherTypeGroup = new javax.swing.ButtonGroup();
        staffGenderGroup = new javax.swing.ButtonGroup();
        navigation = new javax.swing.JTabbedPane();
        mainFrame = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        computerScienceDepartment = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liberalArtsDepartment = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        businessDepartment = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teacherName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        teacherAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        teacherMale = new javax.swing.JRadioButton();
        teacherFemale = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        teacherAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        teacherPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teacherID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        teacherSpecialty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        teacherDegree = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        teacherFullTime = new javax.swing.JRadioButton();
        teacherPartTime = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        teacherHoursWorked = new javax.swing.JTextField();
        addTeacherClear = new javax.swing.JButton();
        addTeacherSubmit = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        teacherDepartment = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        staffName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        staffMale = new javax.swing.JRadioButton();
        staffFemale = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        staffAddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        staffPhone = new javax.swing.JTextField();
        staffAge = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        staffDuty = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        staffWorkload = new javax.swing.JTextField();
        staffClear = new javax.swing.JButton();
        staffSubmit = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        staffDepartment = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR Management System");
        setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        title.setText("Human Resources Management System");

        author.setText("By Aryan Arora");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        computerScienceDepartment.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        computerScienceDepartment.setText("computerScienceDepartment");
        computerScienceDepartment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(computerScienceDepartment);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Engineering", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        liberalArtsDepartment.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        liberalArtsDepartment.setText("liberalArtsDepartment");
        liberalArtsDepartment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane2.setViewportView(liberalArtsDepartment);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Liberal Arts", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBorder(null);

        businessDepartment.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        businessDepartment.setText("businessDepartment");
        businessDepartment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane3.setViewportView(businessDepartment);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Business", jPanel5);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(mainFrameLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(author)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        navigation.addTab("Dashboard", mainFrame);

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel3.setText("Gender");

        teacherGenderGroup.add(teacherMale);
        teacherMale.setText("Male");

        teacherGenderGroup.add(teacherFemale);
        teacherFemale.setText("Female");

        jLabel4.setText("Address");

        jLabel5.setText("Phone Number");

        jLabel6.setText("ID Number");

        jLabel7.setText("Specialty");

        jLabel8.setText("Degree");

        teacherDegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelors", "Masters", "Doctorate (PhD)" }));

        jLabel9.setText("Employment Type");

        teacherTypeGroup.add(teacherFullTime);
        teacherFullTime.setText("Full Time");

        teacherTypeGroup.add(teacherPartTime);
        teacherPartTime.setText("Part Time");

        jLabel10.setText("Work Hours");

        addTeacherClear.setText("Clear");
        addTeacherClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherClearActionPerformed(evt);
            }
        });

        addTeacherSubmit.setText("Submit");
        addTeacherSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherSubmitActionPerformed(evt);
            }
        });

        jLabel18.setText("Department");

        teacherDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engineering", "Liberal Arts", "Business" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(teacherAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(teacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(teacherMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teacherFemale))
                            .addComponent(jLabel3)
                            .addComponent(teacherPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(teacherID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(teacherSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(teacherDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(teacherFullTime)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(teacherPartTime))
                                    .addComponent(jLabel9))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(teacherHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel10)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(teacherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addTeacherSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addTeacherClear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherMale)
                    .addComponent(teacherFemale))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherFullTime)
                    .addComponent(teacherPartTime)
                    .addComponent(teacherHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTeacherSubmit)
                    .addComponent(addTeacherClear))
                .addGap(28, 28, 28))
        );

        navigation.addTab("Add Teacher", jPanel2);

        jLabel11.setText("Name");

        jLabel12.setText("Age");

        jLabel13.setText("Gender");

        staffGenderGroup.add(staffMale);
        staffMale.setText("Male");

        staffGenderGroup.add(staffFemale);
        staffFemale.setText("Female");

        jLabel14.setText("Address");

        jLabel15.setText("Phone Number");

        jLabel16.setText("Duty");

        jLabel17.setText("Workload");

        staffClear.setText("Clear");
        staffClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffClearActionPerformed(evt);
            }
        });

        staffSubmit.setText("Submit");
        staffSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffSubmitActionPerformed(evt);
            }
        });

        jLabel19.setText("Department");

        staffDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engineering", "Liberal Arts", "Business" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(staffAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(staffAge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(staffMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffFemale))
                            .addComponent(jLabel13)
                            .addComponent(staffPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(staffDuty, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(staffWorkload, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(staffDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(staffSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(staffClear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffMale)
                    .addComponent(staffFemale))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffDuty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffWorkload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staffDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffSubmit)
                    .addComponent(staffClear))
                .addGap(29, 29, 29))
        );

        navigation.addTab("Add Staff", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigation)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigation)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTeacherSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherSubmitActionPerformed
        try {
            boolean exists = false;
            String name = teacherName.getText();
            int age = Integer.parseInt(teacherAge.getText());
            String gender = "";
            if(teacherMale.isSelected()){
                gender = "Male";
            } else if(teacherFemale.isSelected()){
                gender = "Female";
            } else {
                JOptionPane.showMessageDialog(null, "No Gender Selected!");
            }
            String address = teacherAddress.getText();
            String phone = teacherPhone.getText();
            int id = Integer.parseInt(teacherID.getText());
            String specialty = teacherSpecialty.getText();
            int degree = teacherDegree.getSelectedIndex() + 1;
            boolean fullTime = false;
            if(teacherFullTime.isSelected()){
                fullTime = true;
            } else if(teacherPartTime.isSelected()){
                fullTime = false;
            } else {
                JOptionPane.showMessageDialog(null, "No Employment Type Selected!");
            }
            int hoursWorked = 32;
            if(!fullTime){
                hoursWorked = Integer.parseInt(teacherHoursWorked.getText());
            }
            int department = teacherDepartment.getSelectedIndex();
            Teacher teacher = new Teacher(name,age, gender, address, phone, id, specialty, degree, false, fullTime, hoursWorked);
            
            for(int i = 0; i < departments.get(department).getTeachers().size(); i++){
                if(departments.get(department).getTeachers().get(i).equals(teacher)){
                    JOptionPane.showMessageDialog(null, name);
                    exists = true;
                }
            }
            
            if(!exists){
                departments.get(department).addTeacher(teacher);
                computerScienceDepartment.setText(departments.get(0).display());
                liberalArtsDepartment.setText(departments.get(1).display());
                businessDepartment.setText(departments.get(2).display());
                driver.saveProgress(departments);
                addTeacherClear.doClick();
                JOptionPane.showMessageDialog(null, "Teacher Added!");
            }
            
        } catch (Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Invalid Submission!");
        }
    }//GEN-LAST:event_addTeacherSubmitActionPerformed

    private void addTeacherClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherClearActionPerformed
        // TODO add your handling code here:
        String t = "";
        teacherName.setText(t);
        teacherAge.setText(t);
        teacherGenderGroup.clearSelection();
        teacherAddress.setText(t);
        teacherPhone.setText(t);
        teacherID.setText(t);
        teacherSpecialty.setText(t);
        teacherDegree.setSelectedIndex(0);
        teacherTypeGroup.clearSelection();
        teacherHoursWorked.setText(t);
        teacherDepartment.setSelectedIndex(0);
    }//GEN-LAST:event_addTeacherClearActionPerformed

    private void staffSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffSubmitActionPerformed
        // TODO add your handling code here:
        try {
            boolean exists = false;
            String name = staffName.getText();
            int age = Integer.parseInt(staffAge.getText());
            String gender = "";
            if(staffMale.isSelected()){
                gender = "Male";
            } else if(staffFemale.isSelected()){
                gender = "Female";
            } else {
                // THROW EXCEPTION
                JOptionPane.showMessageDialog(null, "No Gender Selected!");
            }
            String address = staffAddress.getText();
            String phone = staffPhone.getText();
            String duty = staffDuty.getText();
            int workload = Integer.parseInt(staffWorkload.getText());
            if(workload > 40){
                JOptionPane.showMessageDialog(null, "Staff Workload Cannot Exceed 40!");
                exists = true;
            }
            int department = staffDepartment.getSelectedIndex();
            Staff staff = new Staff(name,age, gender, address, phone, duty, workload);
            
            for(int i = 0; i < departments.get(department).getStaff().size(); i++){
                if(departments.get(department).getStaff().get(i).equals(staff)){
                    JOptionPane.showMessageDialog(null, "Staff Already Exists!");
                    exists = true;
                }
            }
            
            if(!exists){
                departments.get(department).addStaff(staff);
                computerScienceDepartment.setText(departments.get(0).display());
                liberalArtsDepartment.setText(departments.get(1).display());
                businessDepartment.setText(departments.get(2).display());
                driver.saveProgress(departments);
                staffClear.doClick();
                JOptionPane.showMessageDialog(null, "Staff Added!");
            }
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Submission!");
        }
    }//GEN-LAST:event_staffSubmitActionPerformed

    private void staffClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffClearActionPerformed
        // TODO add your handling code here:
        String t = "";
        staffName.setText(t);
        staffAge.setText(t);
        staffGenderGroup.clearSelection();
        staffAddress.setText(t);
        staffPhone.setText(t);
        staffDuty.setText(t);
        staffWorkload.setText(t);
        staffDepartment.setSelectedIndex(0);
    }//GEN-LAST:event_staffClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeacherClear;
    private javax.swing.JButton addTeacherSubmit;
    private javax.swing.JLabel author;
    private javax.swing.JLabel businessDepartment;
    private javax.swing.JLabel computerScienceDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel liberalArtsDepartment;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JTabbedPane navigation;
    private javax.swing.JTextField staffAddress;
    private javax.swing.JTextField staffAge;
    private javax.swing.JButton staffClear;
    private javax.swing.JComboBox<String> staffDepartment;
    private javax.swing.JTextField staffDuty;
    private javax.swing.JRadioButton staffFemale;
    private javax.swing.ButtonGroup staffGenderGroup;
    private javax.swing.JRadioButton staffMale;
    private javax.swing.JTextField staffName;
    private javax.swing.JTextField staffPhone;
    private javax.swing.JButton staffSubmit;
    private javax.swing.JTextField staffWorkload;
    private javax.swing.JTextField teacherAddress;
    private javax.swing.JTextField teacherAge;
    private javax.swing.JComboBox<String> teacherDegree;
    private javax.swing.JComboBox<String> teacherDepartment;
    private javax.swing.JRadioButton teacherFemale;
    private javax.swing.JRadioButton teacherFullTime;
    private javax.swing.ButtonGroup teacherGenderGroup;
    private javax.swing.JTextField teacherHoursWorked;
    private javax.swing.JTextField teacherID;
    private javax.swing.JRadioButton teacherMale;
    private javax.swing.JTextField teacherName;
    private javax.swing.JRadioButton teacherPartTime;
    private javax.swing.JTextField teacherPhone;
    private javax.swing.JTextField teacherSpecialty;
    private javax.swing.ButtonGroup teacherTypeGroup;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
